import React, { useEffect, useMemo, useRef, useState } from "react";
import type { Project } from "../types";
import { createId, getControlDatabase, LOCAL_PARTICIPANT_ID, type ControlConversation, type ControlMessage, type ControlRun, type ControlTask } from "../lib/control-db";
import { dispatchTask } from "../lib/agent-dispatch";
import { getSecretRedactor } from "../lib/core/secret-redactor";
import { invoke } from "../lib/tauri";
import FormDialog from "./FormDialog";
import "./BuildWithAI.css";

type Screenshot = { id: string; file: File; preview: string };

export default function BuildWithAI({ projects, currentProjectId, onClose, onStarted, onCreateProject }: { projects: Project[]; currentProjectId: string; onClose: () => void; onStarted: (taskId: string) => void; onCreateProject: (location:"desktop"|"documents",name:string)=>Promise<Project|undefined>; }) {
  const db=getControlDatabase(),safe=(value:string)=>getSecretRedactor().redact(value).redacted,identities=useRef({workId:createId("work"),conversationId:createId("conversation"),taskId:createId("task")});
  const [projectId,setProjectId]=useState(currentProjectId||"__new__"),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[criteria,setCriteria]=useState(""),[modelPreference,setModelPreference]=useState<NonNullable<ControlTask["modelPreference"]>>("auto");
  const [newProjectName,setNewProjectName]=useState(""),[newProjectLocation,setNewProjectLocation]=useState<"desktop"|"documents">("desktop"),[creatingProject,setCreatingProject]=useState(false),[projectNotice,setProjectNotice]=useState<string>();
  const [phase,setPhase]=useState<"brief"|"clarify">("brief"),[messages,setMessages]=useState<ControlMessage[]>([]),[runs,setRuns]=useState<ControlRun[]>([]),[answer,setAnswer]=useState(""),[submitting,setSubmitting]=useState(false),[error,setError]=useState<string>();
  const [screenshots,setScreenshots]=useState<Screenshot[]>([]),fileInput=useRef<HTMLInputElement>(null),screenshotsRef=useRef<Array<{preview:string}>>([]),attachmentPaths=useRef<string[]>([]);
  const selectedProject=useMemo(()=>projects.find(project=>project.id===projectId),[projects,projectId]),assistantMessages=messages.filter(message=>message.role==="assistant"),latestAssistant=assistantMessages[assistantMessages.length-1],activeRun=runs.some(run=>["queued","starting","running"].includes(run.status)),aiReady=Boolean(latestAssistant?.content.includes("READY_TO_BUILD"));
  useEffect(()=>{screenshotsRef.current=screenshots;},[screenshots]);useEffect(()=>()=>screenshotsRef.current.forEach(item=>URL.revokeObjectURL(item.preview)),[]);
  useEffect(()=>{if(phase!=="clarify")return;const refresh=async()=>{setMessages((await db.messages.find({conversationId:identities.current.conversationId})).sort((a,b)=>a.createdAt-b.createdAt));setRuns((await db.runs.find({workId:identities.current.workId})).filter(run=>run.kind==="conversation"));};void refresh();const stops=[db.messages.subscribe(()=>void refresh()),db.runs.subscribe(()=>void refresh())];return()=>stops.forEach(stop=>stop());},[phase]);
  const addScreenshots=(files:File[])=>{const valid=files.filter(file=>file.type.startsWith("image/")&&file.size<=20*1024*1024);if(valid.length!==files.length)setError("Only PNG, JPEG, WebP, or GIF screenshots up to 20 MB can be attached.");setScreenshots(current=>[...current,...valid.map(file=>({id:createId("attachment"),file,preview:URL.createObjectURL(file)}))].slice(0,12));};
  useEffect(()=>{if(phase!=="brief")return;const paste=(event:ClipboardEvent)=>{const files=Array.from(event.clipboardData?.items||[]).filter(item=>item.kind==="file").map(item=>item.getAsFile()).filter((file):file is File=>file instanceof File&&file.type.startsWith("image/"));if(files.length){event.preventDefault();addScreenshots(files);}};window.addEventListener("paste",paste);return()=>window.removeEventListener("paste",paste);},[phase]);
  const removeScreenshot=(id:string)=>setScreenshots(current=>{const removed=current.find(item=>item.id===id);if(removed)URL.revokeObjectURL(removed.preview);return current.filter(item=>item.id!==id);});
  const createProject=async()=>{const name=newProjectName.trim();if(!name||creatingProject)return;if(!/^[a-zA-Z0-9._-]+$/.test(name))return setError("Folder name may contain letters, numbers, dots, dashes, and underscores.");setCreatingProject(true);setError(undefined);try{const project=await onCreateProject(newProjectLocation,name);if(!project)throw new Error("Control could not create the project");setProjectId(project.id);setProjectNotice(`Created ${project.name} in ${newProjectLocation==="desktop"?"Desktop":"Documents"} with Git initialized.`);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setCreatingProject(false);}};
  const importScreenshots=async()=>{if(attachmentPaths.current.length||!selectedProject)return attachmentPaths.current;const stored:string[]=[];for(const screenshot of screenshots){const bytes=Array.from(new Uint8Array(await screenshot.file.arrayBuffer())),response=await invoke<string>("cmd_task_attachment_write",{workspacePath:selectedProject.path,taskId:identities.current.workId,fileName:screenshot.file.name||`screenshot-${stored.length+1}.png`,bytes});if(!response.success||!response.data)throw new Error(response.error||`Could not attach ${screenshot.file.name}`);stored.push(response.data);}attachmentPaths.current=stored;return stored;};
  const ensureClarification=async():Promise<ControlConversation>=>{if(!selectedProject)throw new Error("Select a project");const existing=await db.conversations.get(identities.current.conversationId);if(existing)return existing;const paths=await importScreenshots(),now=Date.now(),brief=safe(description.trim()),{workId,conversationId}=identities.current;await db.works.insert({id:workId,projectId,title:safe(title.trim()),intent:brief,kind:"feature",status:"awaiting-input",createdAt:now,updatedAt:now},workId);const intelligence=await db.intelligence.get("control-intelligence")||(await db.intelligence.all()).find(item=>item.status==="active");if(!intelligence)throw new Error("Control Intelligence is unavailable. Configure an execution provider in Intelligence settings.");const conversation:ControlConversation={id:conversationId,projectId,workId,agentId:intelligence.id,intelligenceId:intelligence.id,title:`Clarify: ${safe(title.trim())}`,scope:"project",createdAt:now,updatedAt:now};await db.conversations.insert(conversation,conversationId);if(paths.length){const activityId=createId("activity");await db.activity.insert({id:activityId,projectId,workId,type:"screenshots_attached",actor:LOCAL_PARTICIPANT_ID,summary:`Attached ${paths.length} screenshot${paths.length===1?"":"s"} to feature brief`,details:paths.join("\n"),createdAt:now},activityId);}return conversation;};
  const askAI=async(rawContent:string,initial=false)=>{if(!selectedProject||activeRun)return;setSubmitting(true);setError(undefined);try{const conversation=await ensureClarification(),agent=await db.intelligence.get(conversation.agentId);if(!agent)throw new Error("Control Intelligence is unavailable");const prior=(await db.messages.find({conversationId:conversation.id})).sort((a,b)=>a.createdAt-b.createdAt),now=Date.now(),messageId=createId("message"),runId=createId("run"),paths=attachmentPaths.current;const content=initial?`We are defining a feature before implementation. Do not modify files.\n\nFeature: ${title.trim()}\n\nDesired behavior:\n${description.trim()}\n\nAcceptance criteria:\n${criteria.trim()||"Not specified yet"}${paths.length?`\n\nReference screenshots (inspect these):\n${paths.map(path=>`- ${path}`).join("\n")}`:""}\n\nInspect the repository and screenshots read-only. Identify ambiguity, missing edge cases, and conflicts with the existing architecture. Ask no more than five focused questions. If the request is already sufficiently precise, give a concise implementation plan and end with READY_TO_BUILD.`:`My clarification:\n${rawContent.trim()}\n\nReassess the feature using the full conversation. Ask only the remaining essential questions. When the behavior and acceptance criteria are sufficiently precise, provide the agreed implementation plan and end with READY_TO_BUILD.`;await db.messages.insert({id:messageId,conversationId:conversation.id,senderId:LOCAL_PARTICIPANT_ID,role:"user",type:"message",content:safe(content),deliveryStatus:"pending",createdAt:now},messageId);await db.runs.insert({id:runId,projectId,workId:conversation.workId!,kind:"conversation",conversationId:conversation.id,requestMessageId:messageId,agentId:agent.id,intelligenceId:agent.id,runtime:"resolving",routingTier:modelPreference==="local"?"local":"frontier",routingReason:"Build with AI clarification is read-only",status:"starting",startedAt:now},runId);await db.messages.update(messageId,{runId});const history=prior.map(message=>`${message.role}: ${message.content}`).join("\n"),response=await invoke<{pid:number;runtime:string;processStartedAt:number}>("cmd_agent_chat",{runId,projectPath:selectedProject.path,projectName:selectedProject.name,agentName:agent.name,agentInstructions:"Act as a product and software requirements partner. Increase certainty before implementation. Inspect read-only, ask focused questions, propose a concrete plan, and never modify files.",history,content,preferredRuntime:agent.runtime||modelPreference,executionTimeoutMinutes:agent.timeoutMinutes});if(!response.success||!response.data)throw new Error(response.error||"Clarification failed to start");await db.runs.update(runId,{runtime:response.data.runtime,status:"running",pid:response.data.pid,processStartedAt:response.data.processStartedAt});setPhase("clarify");setAnswer("");}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setSubmitting(false);}};
  const approveAndBuild=async()=>{if(!selectedProject||!latestAssistant||activeRun)return;setSubmitting(true);setError(undefined);const {workId,taskId}=identities.current;try{const now=Date.now(),acceptanceCriteria=criteria.split("\n").map(value=>safe(value.trim())).filter(Boolean),transcript=messages.map(message=>`${message.role==="assistant"?"Control Intelligence":"You"}: ${message.content.replace("READY_TO_BUILD","").trim()}`).join("\n\n"),paths=attachmentPaths.current,projectTasks=await db.tasks.find({projectId}),finalDescription=`${safe(description.trim())}${paths.length?`\n\nReference screenshots (inspect these image files before implementing):\n${paths.map(path=>`- ${path}`).join("\n")}`:""}\n\nApproved clarification and plan:\n${safe(transcript)}`;const task:ControlTask={id:taskId,workId,projectId,scope:"project",title:safe(title.trim()),description:finalDescription,status:"not-started",priority:"high",urgency:"normal",tags:["feature","build-with-ai","clarified",...(paths.length?["screenshots-attached"]:[])],blockedBy:[],acceptanceCriteria,feedback:[],modelPreference,order:projectTasks.reduce((highest,item)=>Math.max(highest,item.order??item.createdAt),0)+1,createdAt:now,updatedAt:now};await db.tasks.insert(task,taskId);await db.works.update(workId,{title:task.title,intent:finalDescription,status:"captured",updatedAt:now});const activityId=createId("activity");await db.activity.insert({id:activityId,projectId,workId,taskId,type:"feature_plan_approved",actor:LOCAL_PARTICIPANT_ID,summary:`Approved AI build plan: ${task.title}`,details:latestAssistant.content.replace("READY_TO_BUILD","").trim(),createdAt:now},activityId);await dispatchTask(taskId);onStarted(taskId);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setSubmitting(false);}};
  return <FormDialog title="Build with AI" description={phase==="brief"?"Start with a brief and screenshots. Control Intelligence will clarify the request before any implementation begins.":"Resolve uncertainty with Control Intelligence, then explicitly approve the plan to begin coding."} submitLabel={phase==="brief"?(submitting?"Starting clarification…":"Clarify with AI"):(submitting?"Starting build…":"Approve plan & start building")} disabled={submitting||activeRun||!selectedProject||!title.trim()||!description.trim()||(phase==="clarify"&&!latestAssistant)} onClose={onClose} onSubmit={()=>phase==="brief"?askAI("",true):approveAndBuild()}>
    <div className="build-ai-flow" aria-label="Build workflow"><span className={phase==="brief"?"active":"done"}>1 Brief</span><span className={phase==="clarify"?"active":""}>2 Clarify</span><span>3 Build</span><span>4 Review</span></div>
    {phase==="brief"?<><label>Project<select value={projectId} onChange={event=>{setProjectId(event.target.value);setProjectNotice(undefined);}}>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}<option value="__new__">＋ Build a new project…</option></select></label>{projectId==="__new__"&&<fieldset className="new-project-fields"><legend>New project</legend><label>Folder name<input autoFocus value={newProjectName} onChange={event=>setNewProjectName(event.target.value.replace(/[^a-zA-Z0-9._-]/g,""))} placeholder="my-new-app"/></label><label>Put it in<select value={newProjectLocation} onChange={event=>setNewProjectLocation(event.target.value as "desktop"|"documents")}><option value="desktop">Desktop — default</option><option value="documents">Documents</option></select></label><div className="new-project-git"><span>Git repository</span><strong>Initialized automatically</strong></div><button type="button" className="create-project-button" disabled={creatingProject||!newProjectName.trim()} onClick={()=>void createProject()}>{creatingProject?"Creating project…":"Create project and continue"}</button></fieldset>}{projectNotice&&<div className="project-created-notice">✓ {projectNotice}</div>}<label>Feature name<input value={title} onChange={event=>setTitle(event.target.value)} placeholder="Add customer search" maxLength={120}/></label><label>What should it do?<textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="Describe the user experience, behavior, and important constraints."/></label><label>Done when<textarea value={criteria} onChange={event=>setCriteria(event.target.value)} placeholder={"Users can search by name or email\nEmpty results have a useful message\nExisting tests still pass"}/><small>Optional. Put one acceptance criterion on each line.</small></label>
      <div className="build-ai-attachments"><div><strong>Screenshots</strong><span>Paste, drop, or choose up to 12 images.</span></div><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple hidden onChange={event=>{addScreenshots(Array.from(event.target.files||[]));event.target.value="";}}/><div className="attachment-actions"><button type="button" onClick={()=>fileInput.current?.click()}>＋ Choose screenshots</button><span>or press ⌘V / Ctrl+V below</span></div><div className="screenshot-drop" tabIndex={0} role="button" aria-label="Paste or drop screenshots here" onPaste={event=>{const files=Array.from(event.clipboardData.items).filter(item=>item.kind==="file").map(item=>item.getAsFile()).filter((file):file is File=>Boolean(file));if(files.length){event.preventDefault();addScreenshots(files);}}} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();addScreenshots(Array.from(event.dataTransfer.files));}}>📋 Click here, then paste a screenshot<br/><small>or drag image files here</small></div>{screenshots.length>0&&<div className="screenshot-grid">{screenshots.map(item=><figure key={item.id}><img src={item.preview} alt={item.file.name||"Attached screenshot"}/><figcaption title={item.file.name}>{item.file.name||"Pasted screenshot"}</figcaption><button type="button" aria-label={`Remove ${item.file.name||"screenshot"}`} onClick={()=>removeScreenshot(item.id)}>×</button></figure>)}</div>}</div>
      <label>AI routing<select value={modelPreference} onChange={event=>setModelPreference(event.target.value as NonNullable<ControlTask["modelPreference"]>)}><option value="auto">Automatic — recommended</option><option value="local">Prefer local model</option><option value="frontier">Prefer frontier model</option></select></label><div className="build-ai-safety"><strong>Clarification is read-only</strong><span>The AI may inspect this project and your screenshots, but cannot edit files until you approve its plan.</span></div></>:<><div className={`clarification-status ${aiReady?"ready":"questions"}`}><strong>{activeRun?"Control Intelligence is thinking…":aiReady?"AI says the plan is ready":"Clarification in progress"}</strong><span>{aiReady?"Review the plan below. You still decide whether implementation starts.":"Answer the questions below, or approve when you are satisfied."}</span></div><div className="clarification-thread" aria-live="polite">{messages.map(message=><div className={`clarification-message ${message.role}`} key={message.id}><strong>{message.role==="assistant"?"Control Intelligence":"You"}</strong><div>{message.content.replace("READY_TO_BUILD","").trim()}</div></div>)}{activeRun&&<div className="clarification-thinking">Inspecting the request and repository…</div>}</div><label>Your answer or adjustment<textarea value={answer} disabled={activeRun} onChange={event=>setAnswer(event.target.value)} placeholder="Answer the questions, correct an assumption, or ask for a different plan."/></label><button type="button" className="clarification-send" disabled={activeRun||submitting||!answer.trim()} onClick={()=>void askAI(answer)}>Send and refine plan</button><div className="build-ai-safety"><strong>Approval gate</strong><span>“Approve plan & start building” is the only action here that launches a write-capable coding run. Clarification never edits the repository.</span></div></>}
    {error&&<div className="field-error" role="alert">{error}</div>}
  </FormDialog>;
}
