"use client";
import React,{useEffect,useState} from "react";
import {invoke} from "../lib/tauri";
import {GitStatus} from "../types";
import DiffViewer from "./DiffViewer";
import "./GitPanel.css";

type Commit={hash:string;short_hash:string;message:string;author:string;timestamp:number};
type GitConflict={path:string;kind:string;explanation:string;localExists:boolean;incomingExists:boolean;localPreview:string;incomingPreview:string};
const generatedPath=(path:string)=>/(^|\/)(node_modules|\.next|\.agent-build|\.vercel|\.control|target|dist|build|coverage)(\/|$)/.test(path);
const sensitivePath=(path:string)=>/(^|\/)\.env(?:\..*)?$|(^|\/)(credentials?|secrets?)\.(json|ya?ml|toml)$/i.test(path);
export default function GitPanel({gitStatus,workspacePath,onRefresh,dirtyPaths=[]}:{gitStatus:GitStatus|null;workspacePath?:string;onRefresh:()=>void;dirtyPaths?:string[]}){
 const [tab,setTab]=useState<"changes"|"staged"|"history">("changes"),[selected,setSelected]=useState<string>(),[patch,setPatch]=useState(""),[before,setBefore]=useState(""),[now,setNow]=useState(""),[message,setMessage]=useState(""),[history,setHistory]=useState<Commit[]>([]),[branches,setBranches]=useState<string[]>([]),[busy,setBusy]=useState<string>(),[error,setError]=useState<string>(),[notice,setNotice]=useState<string>();
 const [conflicts,setConflicts]=useState<GitConflict[]>([]);
 const staged=gitStatus?Array.from(gitStatus.stagedFiles):[],allChanges=gitStatus?Array.from(gitStatus.files.entries()).filter(([path,status])=>!gitStatus.stagedFiles.has(path)||status.hasWorktreeChanges):[];
 const changes=allChanges.filter(([path])=>!generatedPath(path)&&!sensitivePath(path)),generatedChanges=allChanges.filter(([path])=>generatedPath(path)),sensitiveChanges=allChanges.filter(([path])=>sensitivePath(path)),recommendedChanges=changes;
 useEffect(()=>{if(tab==="history"&&workspacePath)void invoke<Commit[]>("cmd_git_history",{workspacePath}).then(r=>r.success&&setHistory(r.data||[]));},[tab,workspacePath]);
 useEffect(()=>{if(workspacePath)void invoke<string[]>("cmd_git_branches",{workspacePath}).then(response=>response.success&&setBranches(response.data||[]));},[workspacePath,gitStatus?.branch]);
 const conflictKey=gitStatus?Array.from(gitStatus.files.entries()).filter(([,status])=>status.isConflicted).map(([path])=>path).sort().join("|"):"";
 useEffect(()=>{if(!workspacePath||!conflictKey){setConflicts([]);return;}void invoke<GitConflict[]>("cmd_git_conflicts",{workspacePath}).then(response=>response.success&&setConflicts(response.data||[]));},[workspacePath,conflictKey]);
 const showDiff=async(path:string,isStaged:boolean)=>{if(!workspacePath)return;setSelected(path);const [difference,previous,current]=await Promise.all([invoke<string>("cmd_git_diff",{workspacePath,filePath:path,staged:isStaged}),invoke<string>("cmd_git_file_content",{workspacePath,filePath:path,version:"before"}),invoke<string>("cmd_git_file_content",{workspacePath,filePath:path,version:"now"})]);if(difference.success)setPatch(difference.data||"");else setError(difference.error);setBefore(previous.data||"");setNow(current.data||"");};
 const stage=async(path:string)=>{if(!workspacePath)return;setNotice(undefined);setError(undefined);const r=await invoke("cmd_git_stage",{workspacePath,filePath:path});if(!r.success)setError(r.error);else setNotice(`${path.replace(/\/$/,"")} added to the next commit.`);onRefresh();};
 const stageRecommended=async()=>{if(!workspacePath)return false;for(const [path] of recommendedChanges){const response=await invoke("cmd_git_stage",{workspacePath,filePath:path});if(!response.success){setError(response.error||`Could not stage ${path}`);return false;}}return true;};
 const stageAll=async()=>{if(!workspacePath||busy||!recommendedChanges.length)return;setBusy("stage");setError(undefined);setNotice(undefined);if(!await stageRecommended()){setBusy(undefined);onRefresh();return;}setTab("staged");setNotice(`Staged ${recommendedChanges.length} source file${recommendedChanges.length===1?"":"s"}. Generated folders were left out.`);setBusy(undefined);onRefresh();};
 const unstage=async(path:string)=>{if(!workspacePath)return;const r=await invoke("cmd_git_unstage",{workspacePath,filePath:path});if(!r.success)setError(r.error);onRefresh();};
 const commit=async()=>{if(!workspacePath||!message.trim())return;setNotice(undefined);const r=await invoke<string>("cmd_git_commit",{workspacePath,message:message.trim()});if(r.success){setMessage("");setNotice(`Committed ${r.data?.slice(0,8)||"changes"}. Push to publish it to the remote.`);onRefresh();}else setError(r.error);};
 const stageAndCommit=async()=>{if(!workspacePath||busy||!message.trim())return;setBusy("commit");setError(undefined);setNotice(undefined);if(!await stageRecommended()){setBusy(undefined);onRefresh();return;}const response=await invoke<string>("cmd_git_commit",{workspacePath,message:message.trim()});if(response.success){setMessage("");setNotice(`Committed ${response.data?.slice(0,8)||"changes"}. Push to publish it to the remote.`);}else setError(response.error);setBusy(undefined);onRefresh();};
 const sync=async(action:"fetch"|"pull"|"push")=>{if(!workspacePath||busy)return;setBusy(action);setError(undefined);setNotice(undefined);const response=await invoke<string>("cmd_git_sync",{workspacePath,action});if(!response.success)setError(response.error);else setNotice(response.data?.trim()||(action==="push"?"Local commits were published to the remote.":`${action[0].toUpperCase()+action.slice(1)} completed successfully.`));onRefresh();setBusy(undefined);};
 const switchBranch=async(branch:string,create=false)=>{if(!workspacePath||!branch||busy)return;setBusy("branch");setError(undefined);const response=await invoke<string>("cmd_git_switch_branch",{workspacePath,branch,create});if(!response.success)setError(response.error);else onRefresh();setBusy(undefined);};
 const resolveConflict=async(conflict:GitConflict,resolution:"local"|"incoming"|"resolved")=>{if(!workspacePath||busy)return;const label=resolution==="local"?"your local version":resolution==="incoming"?"the incoming version":"the edited file";if(resolution!=="resolved"&&!window.confirm(`Resolve ${conflict.path} using ${label}? The other version remains recoverable in Git until the merge is committed.`))return;setBusy("resolve");setError(undefined);const response=await invoke("cmd_git_resolve_conflict",{workspacePath,filePath:conflict.path,resolution});if(!response.success)setError(response.error);else setNotice(`${conflict.path} resolved using ${label}. Review it, then commit the merge.`);setBusy(undefined);onRefresh();};
 const autoResolve=async()=>{if(!workspacePath||busy)return;setBusy("resolve");setError(undefined);const response=await invoke<number>("cmd_git_auto_resolve_conflicts",{workspacePath});if(!response.success)setError(response.error);else setNotice(response.data?`Safely resolved ${response.data} conflict${response.data===1?"":"s"}. Ambiguous conflicts still need your choice.`:"No conflict was safe to resolve automatically. Choose a version or edit manually.");setBusy(undefined);onRefresh();};
 if(!gitStatus)return <div className="git-panel"><div className="git-empty">Not a Git repository</div></div>;
 return <div className="git-panel"><div className="git-header"><div className="git-branch">🌿 <select aria-label="Current Git branch" value={gitStatus.branch} onChange={event=>void switchBranch(event.target.value)} disabled={!!busy}>{branches.map(branch=><option key={branch}>{branch}</option>)}</select>{!gitStatus.isClean&&<span className="modified-indicator" title="Repository has uncommitted changes">●</span>}<span>{gitStatus.ahead?`↑${gitStatus.ahead}`:""}{gitStatus.behind?` ↓${gitStatus.behind}`:""}</span></div>{gitStatus.ahead>0&&<div className="push-ready"><strong>{gitStatus.ahead} commit{gitStatus.ahead===1?"":"s"} ready to publish</strong><span>Push can publish {gitStatus.ahead===1?"it":"them"} without including your uncommitted files.</span></div>}<div className="decision-options"><button disabled={!!busy} onClick={()=>void sync("fetch")}>Check remote</button><button disabled={!!busy} onClick={()=>void sync("pull")}>Pull</button><button className={gitStatus.ahead?"push-primary":""} disabled={!!busy} onClick={()=>void sync("push")} title="Publish existing local commits; uncommitted files are not included">{busy==="push"?"Pushing…":gitStatus.ahead?`Push ${gitStatus.ahead} commit${gitStatus.ahead===1?"":"s"}`:"Push"}</button><button disabled={!!busy} onClick={()=>{const branch=window.prompt("New branch name")?.trim();if(branch)void switchBranch(branch,true);}}>+ Branch</button></div></div><div className="git-tabs"><button className={tab==="changes"?"git-tab active":"git-tab"} onClick={()=>setTab("changes")}>Not committed <span className="badge">{changes.length}</span></button><button className={tab==="staged"?"git-tab active":"git-tab"} onClick={()=>setTab("staged")}>Ready to commit <span className="badge">{staged.length}</span></button><button className={tab==="history"?"git-tab active":"git-tab"} onClick={()=>setTab("history")}>History</button></div>{error&&<div className="tasks-error">{error}</div>}{notice&&<div className="git-notice">{notice}</div>}<div className="git-content">
 {conflicts.length>0&&<div className="git-conflicts"><div className="conflict-heading"><strong>{conflicts.length} merge conflict{conflicts.length===1?"":"s"}</strong><span>Git paused the pull because both sides touched the same work. Resolve every file, review, then commit.</span><button disabled={!!busy} onClick={()=>void autoResolve()}>Resolve Safe Conflicts</button></div>{conflicts.map(conflict=><div className="conflict-card" key={conflict.path}><strong>{conflict.path}</strong><p>{conflict.explanation}</p>{conflict.localPreview&&<details><summary>Your local version</summary><pre>{conflict.localPreview}</pre></details>}{conflict.incomingPreview&&<details><summary>Incoming version</summary><pre>{conflict.incomingPreview}</pre></details>}<div className="decision-options"><button disabled={!!busy} onClick={()=>void resolveConflict(conflict,"local")}>{conflict.localExists?"Keep Local":"Keep Local Deletion"}</button><button disabled={!!busy} onClick={()=>void resolveConflict(conflict,"incoming")}>{conflict.incomingExists?"Use Incoming":"Accept Incoming Deletion"}</button><button disabled={!!busy} onClick={()=>{onRefresh();void showDiff(conflict.path,false);}}>Review/Edit</button><button disabled={!!busy} onClick={()=>void resolveConflict(conflict,"resolved")}>Mark Edited File Resolved</button></div></div>)}</div>}
 {tab==="changes"&&<>{dirtyPaths.length>0&&<div className="git-working-summary unsaved"><strong>{dirtyPaths.length} unsaved editor change{dirtyPaths.length===1?"":"s"}</strong><span>{dirtyPaths.join(", ")} · Save with ⌘S before committing.</span></div>}{sensitiveChanges.length>0&&<div className="protected-changes"><strong>Protected from commits</strong><span>Control will not stage local environment or credential files.</span>{sensitiveChanges.map(([path])=><div key={path}>🔒 {path}</div>)}</div>}{staged.length>0&&<div className="git-working-summary next-step"><strong>Next: commit {staged.length} prepared file{staged.length===1?"":"s"}</strong><span>Open “Ready to commit” and describe the change. Existing commits can be pushed at any time.</span><button onClick={()=>setTab("staged")}>Continue to commit</button></div>}{recommendedChanges.length>0&&<><div className="git-working-summary"><strong>{recommendedChanges.length} source change{recommendedChanges.length===1?" is":"s are"} not prepared</strong><span>Add a description below to include {staged.length?"these with the prepared files":"these files"} in one commit. Protected files are never included.</span></div><div className="commit-section commit-section-top"><textarea aria-label="Commit description" className="commit-message" placeholder="Describe what changed and why" value={message} onChange={event=>setMessage(event.target.value)}/><button className="commit-button" disabled={!!busy||!message.trim()} onClick={()=>void stageAndCommit()}>Include all source changes &amp; commit</button></div></>}{changes.length?<>{changes.map(([path,status])=><div className="change-item" key={path}><span className="status-badge">{status.status}</span><span className="file-path" onClick={()=>void showDiff(path,false)} title={path}>{path}</span><button aria-label={`Prepare ${path} for commit`} title="Prepare for commit" onClick={()=>void stage(path)}>+</button></div>)}</>:<div className="empty">No source changes waiting to be prepared</div>}{generatedChanges.length>0&&<details className="generated-changes"><summary>{generatedChanges.length} generated or deployment folder{generatedChanges.length===1?"":"s"} excluded</summary><p>Control leaves local build output out of source commits. Add these paths to .gitignore if they should always stay local.</p>{generatedChanges.map(([path])=><div key={path}>{path}</div>)}</details>}</>}
 {tab==="staged"&&<>{staged.length>0&&<div className="commit-section commit-section-top"><div className="git-working-summary next-step"><strong>Next: create a commit from {staged.length} file{staged.length===1?"":"s"}</strong><span>A commit records this prepared snapshot. Afterward, Push publishes it.</span></div><textarea aria-label="Commit description" className="commit-message" placeholder="Describe what changed and why" value={message} onChange={e=>setMessage(e.target.value)}/><button className="commit-button" disabled={!!busy||!message.trim()} onClick={()=>void commit()}>Commit {staged.length} file{staged.length===1?"":"s"}</button></div>}<div>{staged.length?staged.map(path=><div className="change-item" key={path}><span className="checkmark">✓</span><span className="file-path" onClick={()=>void showDiff(path,true)} title={path}>{path}</span><button aria-label={`Remove ${path} from the next commit`} title="Remove from next commit" onClick={()=>void unstage(path)}>−</button></div>):<div className="empty">Nothing is prepared for a commit</div>}</div></>}
 {tab==="history"&&(history.length?history.map(commit=><div className="commit-item" key={commit.hash}><span className="commit-hash">{commit.short_hash}</span><span className="commit-message">{commit.message}</span><span className="commit-time">{commit.author} · {new Date(commit.timestamp*1000).toLocaleDateString()}</span></div>):<div className="empty">No commits</div>)}
 </div>{selected&&<div className="diff-viewer-modal"><div className="modal-header"><span>{selected}</span><button className="close-button" onClick={()=>setSelected(undefined)}>×</button></div><DiffViewer patch={patch} before={before} now={now}/></div>}</div>;
}
