import React,{useEffect,useState} from "react";
import {getControlDatabase,type ControlInboxItem,type ControlParticipant,type ControlWork} from "../lib/control-db";
import type {Project} from "../types";
import "./CoordinationPanel.css";

export default function GlobalInbox({items,knownProjects}:{items:ControlInboxItem[];knownProjects:Project[]}){
  const db=getControlDatabase(),[people,setPeople]=useState<ControlParticipant[]>([]),[works,setWorks]=useState<ControlWork[]>([]),[busy,setBusy]=useState<string>(),[error,setError]=useState<string>();
  const refresh=async()=>{const [participants,allWorks]=await Promise.all([db.participants.all(),db.works.all()]);setPeople(participants);setWorks(allWorks);};
  useEffect(()=>{void refresh();const stops=[db.participants.subscribe(()=>void refresh()),db.works.subscribe(()=>void refresh())];return()=>stops.forEach(stop=>stop());},[]);
  const newCount=items.filter(item=>item.status==="open").length;
  const updateStatus=async(item:ControlInboxItem,status:"acknowledged"|"acted")=>{if(busy)return;setBusy(item.id);setError(undefined);try{await db.inboxItems.update(item.id,{status,updatedAt:Date.now(),actedAt:status==="acted"?Date.now():undefined});}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(undefined);}};
  const conversationAction=(item:ControlInboxItem,action:"reply"|"retry")=>window.dispatchEvent(new CustomEvent("control-inbox-action",{detail:{action,conversationId:item.conversationId,taskId:item.taskId,title:item.title}}));
  const openTask=(item:ControlInboxItem)=>window.dispatchEvent(new CustomEvent("control-inbox-action",{detail:{action:"task",taskId:item.taskId}}));
  return <div className="decision-list global-inbox"><div className="scope-heading"><strong>Global Inbox</strong><span>{newCount} new · {items.length} open across {new Set(items.map(item=>item.projectId)).size} projects</span></div>{error&&<div className="tasks-error">{error}</div>}{!items.length&&<div className="coordination-empty">Global inbox clear</div>}{items.map(item=><div className={`decision-card inbox-card inbox-${item.type} ${item.status==="open"?"is-new":"is-read"}`} key={item.id}><strong><span className="inbox-type-dot"/>{item.type}: {item.title}{item.status==="open"&&<span className="new-label">New</span>}</strong><p>{knownProjects.find(project=>project.id===item.projectId)?.name||"Unknown project"} · {works.find(work=>work.id===item.workId)?.title||"Work"}</p><p>{people.find(person=>person.id===item.fromParticipantId)?.name||item.fromParticipantId} → you</p>{item.body&&<div className="run-summary">{item.body}</div>}<div className="decision-options">{item.conversationId&&<button disabled={busy===item.id} onClick={()=>conversationAction(item,"reply")}>Reply</button>}{item.conversationId&&item.type==="escalation"&&<button disabled={busy===item.id} onClick={()=>conversationAction(item,"retry")}>Try Again</button>}{item.taskId&&<button disabled={busy===item.id} onClick={()=>openTask(item)}>{item.type==="review"?"Review Task":"Open Task"}</button>}{item.status==="open"&&<button disabled={busy===item.id} onClick={()=>void updateStatus(item,"acknowledged")}>Acknowledge</button>}<button disabled={busy===item.id} onClick={()=>void updateStatus(item,"acted")}>Done</button></div></div>)}</div>;
}
